[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal.family = "SF Mono"
bold.family = "SF Mono"
italic.family = "SF Mono"  
bold_italic.family = "SF Mono"
size = 18.0
