general.import = ["~/.config/alacritty/base16-black-metal.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "IosevkaNerdFont"
style = "Bold"

[font.bold_italic]
family = "IosevkaNerdFont"
style = "Bold Italic"

[font.italic]
family = "IosevkaNerdFont"
style = "Italic"

[font.normal]
family = "IosevkaNerdFont"
style = "Regular"
