unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm-256color:Tc'

bind c new-window -c "#{pane_current_path}"

# Add binding to reload tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind \` switch-client -t'{marked}'

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

bind Space last-window

bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

set -sg escape-time 0

set -g extended-keys on
set -g extended-keys-format csi-u

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Use vim-style copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# status bar
set-option -g status-position top
set -g status-right '#(date +"%I:%M%p %d-%m-%Y")#[default]'


# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux'
# set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# catppuccin
# set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "%R %d-%b-%y "
set -ag status-right "#{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
